//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HollyDaysV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int IdSAP { get; set; }
        public string Nombre { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> estatus { get; set; }
        public string area { get; set; }
        public string banda { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<int> dias_disponibles { get; set; }
        public Nullable<System.DateTime> ultimo_desconecte { get; set; }
        public string url_poliza { get; set; }
        public Nullable<int> Idsap_padre { get; set; }
    }
}
