//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HollyDaysV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes
    {
        public int id_solicitud { get; set; }
        public Nullable<int> is_sap { get; set; }
        public string tipo_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string observaciones_solicitante { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<int> id_sap_aprobador { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public string observacion_aprobador { get; set; }
    }
}
